name: Branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  gradle-build:
    name: perform gradle build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

