name: Check PR commits

on:
  pull_request:
    branches: [main]

jobs:
  pr-build-check:
    name: check all commits build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build check
        run: deno run --allow-net --allow-env .github/scripts/check-pr-commits.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
