name: Conventional Commit Check

on:
  pull_request:
    branches: [main]

jobs:
  commit-check:
    name: check conventional commit compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Conventional commits check
        uses: cocogitto/cocogitto-action@v3
